name: Docker CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE: pdf-unlocker-backend
  FRONTEND_IMAGE: pdf-unlocker-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      deployments: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.BACKEND_IMAGE }}
          ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.FRONTEND_IMAGE }}

    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.BACKEND_IMAGE }}:latest
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.FRONTEND_IMAGE }}:latest
        labels: ${{ steps.meta.outputs.labels }}

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Update docker-compose.yml for GitHub Container Registry
      run: |
        sed -i "s|gangadharrr/pdf-unlocker-backend|${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.BACKEND_IMAGE }}|g" docker-compose.yml
        sed -i "s|gangadharrr/pdf-unlocker-frontend|${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.FRONTEND_IMAGE }}|g" docker-compose.yml
        cat docker-compose.yml

    - name: Start application
      run: |
        sudo docker-compose up -d
        echo "Waiting for services to start..."
        sleep 30

    - name: Check running containers
      run: docker ps

    - name: Check backend health
      run: |
        curl -f http://localhost:8000/health || exit 1
        echo "Backend is healthy"

    - name: Check frontend accessibility
      run: |
        curl -f http://localhost:80 || exit 1
        echo "Frontend is accessible"

    - name: Create deployment
      if: success() && github.event_name == 'push'
      uses: chrnorm/deployment-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        environment: production
        initial-status: success
        description: 'Deployed via GitHub Actions'

    - name: Application URLs
      run: |
        echo "✅ Application is running!"
        echo "📱 Frontend URL: http://localhost"
        echo "🔧 Backend URL: http://localhost:8000"
        echo "🏥 Health check: http://localhost:8000/health"
