name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_USERNAME: gangadharrr
  IMAGE_NAME_BACKEND: pdf-unlocker-backend
  IMAGE_NAME_FRONTEND: pdf-unlocker-frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build backend image
      run: |
        cd backend
        docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME_BACKEND }}:latest .
        cd ..
      
    - name: Build frontend image
      run: |
        cd frontend
        docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME_FRONTEND }}:latest .
        cd ..

    - name: List built images
      run: docker images

    - name: Check Docker login status
      run: |
        if ! docker info >/dev/null 2>&1; then
          echo "Docker daemon is not running"
          exit 1
        fi
        echo "Docker daemon is running"
        
    - name: Docker Login
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Push images
      if: github.event_name != 'pull_request' && success()
      run: |
        docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME_BACKEND }}:latest
        docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME_FRONTEND }}:latest
